/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartList: typeof import('./src/components/ChartList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
  }
}
